services:
  flare-bypasser :
    build:
      args:
        #CHROME_VERSION: '131.'
        UID: 1000
        CHROME_DISABLE_GPU: true
        CHECK_SYSTEM: true
        PYTHON_VERSION: 3.11
      context: /home/pi/docker/flare-bypasser/
      dockerfile: /home/pi/docker/flare-bypasser/Dockerfile
    environment:
      # UNUSED: "false"
      # FORKS: "5:3" #< Uncomment if you work with sites with ustable challenge loading (start additional 3 forks after 5 seconds).
      DEBUG: "true"
      # VERBOSE: "true"
      # HTTP_PROXY: "http://192.168.92.200:8888"
      SAVE_CHALLENGE_SCREENSHOTS: "true"
      TZ: America/New_York
    container_name: flare-bypasser
    image: flare-bypasser:latest
    ports:
      - 20080:8080
    #volumes:
      #- ./var:/opt/flare_bypasser/var/
      #< Uncomment if you persistent logs between runs
      #- ./examples/custom_user_commands/:/opt/flare_bypasser/extensions/
      #< Uncomment for run with extension example (/command/my-click uri)
